network.lobby.floors={\
	1: "File DV6",\
	2: "Password DV6",\
	3: "Password DV8",\
	4: "Skunk",\
	5: "Wisp",\
	6: "Killer"\
}

network.basic.floors={\
	3: "Hellhound", \
	4: "Sabertooth", \
	5: "Raven x2", \
	6: "Hellhound", \
	7: "Wisp", \
	8: "Raven", \
	9: "Password DV6",\
	10: "File DV6", \
	11: "Control Node DV6", \
	12: "Password DV6", \
	13: "Skunk", \
	14: "Asp", \
	15: "Scorpion", \
	16: "Killer, Skunk" ,\
	17: "Wisp x3", \
	18: "Liche" \
}